server:
  port: 8090
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    #表示表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    #这样写是否起作用？？
    fetch-registry: false
    #表示是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    register-with-eureka: false
  server:
    #开发时关闭自我保护
    enable-self-preservation: false

#指定应用姓名
spring:
  application:
    name: eureka-server
